workflows:
  ionic-ios:
    name: Ionic iOS Build

    environment:
      node: latest

      groups:
        - ios   # 👈 IMPORTANTE

    working_directory: mobile/alesport-app

    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps

      - name: Build web app
        script: npm run build

      - name: Clean iOS
        script: rm -rf ios

      - name: Add iOS platform
        script: |
          npm install -g @capacitor/cli
          npx cap add ios

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build iOS
        script: |
          cd ios/App
      
          # Crear archivo con la key
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 --decode > key.p8
      
          xcodebuild -project App.xcodeproj \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
          CODE_SIGN_STYLE=Automatic \
          -allowProvisioningUpdates \
          -authenticationKeyPath "$PWD/key.p8" \
          -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
          -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
          -archivePath $CM_BUILD_DIR/App.xcarchive \
          archive

    artifacts:
      - mobile/alesport-app/ios/App/build/**/*.ipa