workflows:
  ionic-ios:
    name: Ionic iOS Build

    environment:
      node: latest

    working_directory: mobile/alesport-app

    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps

      - name: Build web app
        script: npm run build

      - name: Clean iOS
        script: rm -rf ios

      - name: Add iOS platform
        script: |
          npm install -g @capacitor/cli
          npx cap add ios

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -project App.xcodeproj \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $CM_BUILD_DIR/App.xcarchive archive

    artifacts:
      - mobile/alesport-app/ios/App/build/**/*.ipa